/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 scene.gltf --transform
Author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hubble-space-telescope-3de6ad7aa5ef4401be6438a25615ff64
Title: Hubble Space Telescope
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_0} skeleton={nodes.Object_48.skeleton} scale={0.01} />
        <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_0} skeleton={nodes.Object_51.skeleton} scale={0.01} />
        <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} skeleton={nodes.Object_54.skeleton} scale={0.01} />
        <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.material_0} skeleton={nodes.Object_57.skeleton} scale={0.01} />
        <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} skeleton={nodes.Object_60.skeleton} scale={0.01} />
        <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.material_0} skeleton={nodes.Object_63.skeleton} scale={0.01} />
        <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} skeleton={nodes.Object_66.skeleton} scale={0.01} />
        <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.material_0} skeleton={nodes.Object_69.skeleton} scale={0.01} />
        <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} skeleton={nodes.Object_72.skeleton} scale={0.01} />
        <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.material_0} skeleton={nodes.Object_75.skeleton} scale={0.01} />
        <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} skeleton={nodes.Object_78.skeleton} scale={0.01} />
        <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_0} skeleton={nodes.Object_81.skeleton} scale={0.01} />
        <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_0} skeleton={nodes.Object_84.skeleton} scale={0.01} />
        <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_13} skeleton={nodes.Object_87.skeleton} scale={0.01} />
        <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material_13} skeleton={nodes.Object_90.skeleton} scale={0.01} />
        <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.material_13} skeleton={nodes.Object_93.skeleton} scale={0.01} />
        <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material_13} skeleton={nodes.Object_96.skeleton} scale={0.01} />
        <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.material_13} skeleton={nodes.Object_99.skeleton} scale={0.01} />
        <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_13} skeleton={nodes.Object_102.skeleton} scale={0.01} />
        <skinnedMesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.material_13} skeleton={nodes.Object_105.skeleton} scale={0.01} />
        <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_13} skeleton={nodes.Object_108.skeleton} scale={0.01} />
        <skinnedMesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.material_13} skeleton={nodes.Object_111.skeleton} scale={0.01} />
        <skinnedMesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_13} skeleton={nodes.Object_114.skeleton} scale={0.01} />
        <skinnedMesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.material_13} skeleton={nodes.Object_117.skeleton} scale={0.01} />
        <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_0} skeleton={nodes.Object_120.skeleton} scale={0.01} />
        <skinnedMesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.material_13} skeleton={nodes.Object_123.skeleton} scale={0.01} />
        <skinnedMesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_13} skeleton={nodes.Object_126.skeleton} scale={0.01} />
        <skinnedMesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.material_13} skeleton={nodes.Object_129.skeleton} scale={0.01} />
        <skinnedMesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_13} skeleton={nodes.Object_132.skeleton} scale={0.01} />
        <skinnedMesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.material_13} skeleton={nodes.Object_135.skeleton} scale={0.01} />
        <skinnedMesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material_13} skeleton={nodes.Object_138.skeleton} scale={0.01} />
        <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.material_13} skeleton={nodes.Object_141.skeleton} scale={0.01} />
        <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.material_13} skeleton={nodes.Object_144.skeleton} scale={0.01} />
        <skinnedMesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.material_13} skeleton={nodes.Object_147.skeleton} scale={0.01} />
        <skinnedMesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.material_13} skeleton={nodes.Object_150.skeleton} scale={0.01} />
        <skinnedMesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.material_13} skeleton={nodes.Object_153.skeleton} scale={0.01} />
        <skinnedMesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material_13} skeleton={nodes.Object_156.skeleton} scale={0.01} />
        <skinnedMesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.material_13} skeleton={nodes.Object_159.skeleton} scale={0.01} />
        <skinnedMesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.material_13} skeleton={nodes.Object_162.skeleton} scale={0.01} />
        <skinnedMesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.material_13} skeleton={nodes.Object_165.skeleton} scale={0.01} />
        <skinnedMesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.material_13} skeleton={nodes.Object_168.skeleton} scale={0.01} />
        <skinnedMesh name="Object_171" geometry={nodes.Object_171.geometry} material={materials.material_13} skeleton={nodes.Object_171.skeleton} scale={0.01} />
        <skinnedMesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.material_13} skeleton={nodes.Object_174.skeleton} scale={0.01} />
        <skinnedMesh name="Object_177" geometry={nodes.Object_177.geometry} material={materials.material_13} skeleton={nodes.Object_177.skeleton} scale={0.01} />
        <skinnedMesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.material_13} skeleton={nodes.Object_180.skeleton} scale={0.01} />
        <skinnedMesh name="Object_183" geometry={nodes.Object_183.geometry} material={materials.material_13} skeleton={nodes.Object_183.skeleton} scale={0.01} />
        <skinnedMesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.material_13} skeleton={nodes.Object_186.skeleton} scale={0.01} />
        <skinnedMesh name="Object_189" geometry={nodes.Object_189.geometry} material={materials.material_13} skeleton={nodes.Object_189.skeleton} scale={0.01} />
        <skinnedMesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.material_13} skeleton={nodes.Object_192.skeleton} scale={0.01} />
        <skinnedMesh name="Object_195" geometry={nodes.Object_195.geometry} material={materials.material_13} skeleton={nodes.Object_195.skeleton} scale={0.01} />
        <skinnedMesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.material_13} skeleton={nodes.Object_198.skeleton} scale={0.01} />
        <skinnedMesh name="Object_201" geometry={nodes.Object_201.geometry} material={materials.material_13} skeleton={nodes.Object_201.skeleton} scale={0.01} />
        <skinnedMesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.material_13} skeleton={nodes.Object_204.skeleton} scale={0.01} />
        <skinnedMesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.material_13} skeleton={nodes.Object_207.skeleton} scale={0.01} />
        <skinnedMesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.material_13} skeleton={nodes.Object_210.skeleton} scale={0.01} />
        <skinnedMesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.material_13} skeleton={nodes.Object_213.skeleton} scale={0.01} />
        <skinnedMesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.material_13} skeleton={nodes.Object_216.skeleton} scale={0.01} />
        <skinnedMesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.material_13} skeleton={nodes.Object_219.skeleton} scale={0.01} />
        <skinnedMesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.material_13} skeleton={nodes.Object_222.skeleton} scale={0.01} />
        <skinnedMesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.material_13} skeleton={nodes.Object_225.skeleton} scale={0.01} />
        <skinnedMesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.material_13} skeleton={nodes.Object_228.skeleton} scale={0.01} />
        <skinnedMesh name="Object_231" geometry={nodes.Object_231.geometry} material={materials.material_13} skeleton={nodes.Object_231.skeleton} scale={0.01} />
        <skinnedMesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.material_13} skeleton={nodes.Object_234.skeleton} scale={0.01} />
        <skinnedMesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.material_13} skeleton={nodes.Object_237.skeleton} scale={0.01} />
        <skinnedMesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.material_13} skeleton={nodes.Object_240.skeleton} scale={0.01} />
        <skinnedMesh name="Object_243" geometry={nodes.Object_243.geometry} material={materials.material_13} skeleton={nodes.Object_243.skeleton} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
